### ISSUE TITLE
topLayoutGuide issue

### ISSUE THREAD

**Issue by matphillips** [exchangegroup/Dodo#17]
When using the recommended: 
`view.dodo.topLayoutGuide = topLayoutGuide`

The following warning is thrown:
`'topLayoutGuide' was deprecated in iOS 11.0`

What's the best-practice way to resolve this? Previously, with specifying the layout guide, the Dodo banner would fall behind the status bars.

**Comment by evgenyneu** [comment]
@matphillips, thanks for letting me know! Now we will have to support this. Thank you, Apple, for the "bezelless" iPhone X! 

One workaround would be to set the "iOS Deployment target" in the project settings to a version lower than 11.0. This will get rid of the warning. Will it work for you in the short term?

**Comment by matphillips** [comment]
The warning isn't a problem and I need to do some further testing to look for workarounds and perhaps rebuild the views. Thanks

**Comment by evgenyneu** [comment]
"The warning isn't a problem"

Sorry, I probably misunderstood you. When you set `dodo.topLayoutGuide = topLayoutGuide`, does it move the Dodo message bar below the status bar? If it does not, make sure `dodo.topLayoutGuide = topLayoutGuide` is called **before** you show the message.

**Comment by matphillips** [comment]
With `view.dodo.topLayoutGuide = topLayoutGuide` in the code, the notification is shown below the Navigation Bar in both iOS10 and iOS11 and iPhone 7/8/X
But, Xcode warns that this is deprecated in iOS11, so it is likely to stop working in future releases.

Without that command, the notification appears at the top of the view, and sometimes 'behind' the Navigation bar, and on an iPhoneX it is partially hidden by the Sensor Array.

Therefore, Dodo must align to `view.safeAreaLayoutGuide.topAnchor` but just substituting with the line `view.dodo.topLayoutGuide = view.safeAreaLayoutGuide.topAnchor`is not sufficient as it is not a direct replacement and generates errors/crashes.

**Comment by evgenyneu** [comment]
Thanks for the clarification.

> Therefore, Dodo must align to view.safeAreaLayoutGuide.topAnchor

This needs to be implemented, you are right. Thank you for doing the reasearch.

**Comment by clayellis** [comment]
@evgenyneu Have you updated Dodo to use `view.safeAreaLayoutGuide.top/bottomAnchor` yet? Or does this still need work?

**Comment by evgenyneu** [comment]
@clayellis, no I have not done it yet. I'm quite busy right now, week 11 in the university, but I will work on it after exams are over, in about a month or two, I promise. :)

The previous method with layout guides (`view.dodo.topLayoutGuide = topLayoutGuide`) will continue to work for years. We can rely on that because Apply has to support iOS versions older than 11. If the deprecation warning bothers you, I would suggest to set "iOS Deployment target" in the project settings to iOS 10 or older.

**Comment by evgenyneu** [comment]
I've looked at the safe area thing. I have not figured out how to get rid of the layout guides at the moment without changing the API of the library and dropping support for iOS 8. In addition, there is a keyboard evasion code that moves the message view that is positioned at the bottom when the keyboard appears. And that code relies on supplying bottomLayoutGuide because the guide contains the height (of the bottom tab bar, for example). So if I remove bottom layout guide from the library, the message will no longer move from under the keyboard, unless I find a way how to do that with safe area anchors.

I've tested the current library with safe areas in the storyboards, it works without problems right now. The only issue for me is the deprecation warning ('topLayoutGuide' was deprecated in iOS 11.0), that appears only when I set deployment target to iOS 11. Let me know if you have any other issues with keeping the layout guides in the library.

**Comment by clayellis** [comment]
I would just observe `UIKeyboardWillChangeFrame` internally and adjust the position when the keyboard frame changes. Honestly, the keyboard thing is a non-issue to me. What is an issue to me is using a framework that causes warnings in my codebase. Also, I hate to break it to you, but it's time to leave iOS 8 behind. Devices running iOS 8 are likely below 2% at this point. https://developer.apple.com/support/app-store/

**Comment by evgenyneu** [comment]
Thanks, @clayellis, I hear you :). I will think how to solve this problem.

**Comment by evgenyneu** [comment]
The dependency on the layout guides has been removed in version 11. Now one can use the anchors from the safe area or layout guides, as shown in the [setup section](https://github.com/evgenyneu/Dodo#show-and-hide-message-bar) of the readme.

**Comment by matphillips** [comment]
Woo! Looks like a fair bit of work. Thank you for resolving this. I tend to avoid using 3rd party plugins in my code because of this reason, where you rely on something but the developer abandons the code but that is very much not the case with Dodo, you've done great work here- thanks!

**Comment by clayellis** [comment]
Thanks, @evgenyneu!

**Comment by evgenyneu** [comment]
Closing this issue, since the feature has been implemented. Thanks everyone.

**Comment by goktugaral** [comment]
Hello, 
Thanks for this lib, I wanted to give a shot.
I use dodo view on my UIApplication.shared.window and my dodo view was on my status bar. TopAchor thing did not worked on me;
```
 view.dodo.topAnchor = view.safeAreaLayoutGuide.topAnchor
 view.dodo.bottomAnchor = view.safeAreaLayoutGuide.bottomAnchor
```
Maybe I missed something but luckly I have found what I was looking;
```
view.dodo.style.bar.marginToSuperview = CGSize(width: 5, height: 20)
```
I just wanted to write it, it saved me!
